.Dd September 18, 2024
.Dt PWN3T.RU 7
.Os pwn3t.ru
.
.Sh NAME
.Nm pwn3t.ru
.Nd some site in the net
.
.Sh DESCRIPTION
This is domain
where I will host something.
It may be either
an api or
some web app or
someone else's project.
.
.Pp
This page contains list of things
that are being hosted
on this domain.
.
.Pp
These are projects that
were written for
improving QoL while
using discord:
.Bl -tag -width Ds
.It Lk https://ptc.pwn3t.ru/ "PetTheCord"
API to pet users on github
.It Lk https://stp.pwn3t.ru/ "SVG to PNG"
API for converting SVG images to PNG ones
.It Lk https://latexds.pwn3t.ru/ "LaTeXDS"
.Lk https://github.com/latexds "Discord bot"
to render LaTeX expressions
.El
.
.Sh AUTHOR
The
.Nm
domain
is pwn3t by
.An Nakidai Perumenei Aq Mt nakidai@disroot.org
